name: Java CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x mvnw

 #     - name: Run Unit Tests
 #       run: ./mvnw test
